# Generated by Django 4.2.4 on 2023-08-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='upload_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
