# Generated by Django 4.2.4 on 2023-08-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
