# Generated by Django 4.2.4 on 2023-08-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='name',
        ),
    ]
